name: TSV Kalender Update

on:
  schedule:
    - cron: "0 4 * * *"   # täglich um 04:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_PUSH }}

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Phyton Pfad setzen
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

     # - name: Arbeitsverzeichnis setzen
     #   run: cd $GITHUB_WORKSPACE

      - name: Abhängigkeiten installieren
        run: pip install requests ics beautifulsoup4 lxml

      - name: Kalender generieren
        run: python scripts/generate_calendars.py

      - name: Änderungen committen
        run: |
          git config user.name "TSV Kalender Bot"
          git config user.email "fussballjugendobmann@tsv-nieukerk.de"
          git add kalender/*.ics
          git commit -m "Automatische Kalender-Aktualisierung" || echo "Keine Änderungen"

      - name: Pull Request erstellen
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_PUSH }}
          commit-message: "Automatische Kalender-Aktualisierung"
          title: "Automatische Kalender-Aktualisierung"
          body: "Neue Kalenderdateien wurden generiert."
          branch: kalender-update
          merge-method: squash
          auto-merge: true

- name: Pull Request erstellen
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_PUSH }}
          commit-message: "Automatische Kalender-Aktualisierung"
          title: "Automatische Kalender-Aktualisierung"
          body: "Neue Kalenderdateien wurden generiert."
          branch: kalender-update

      - name: Pull Request automatisch mergen
        if: steps.cpr.outputs.pull-request-url != ''
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PAT_PUSH }}


